name: OnCI
on:
  status
jobs:
  build:
    name: 'CI'
    if: ${{ contains(github.event.branches.*.name, 'staging_candidate') }}
    runs-on: ubuntu-latest
    steps:
#      - uses: actions/checkout@v2
#        with:
#          fetch-depth: 100
#          echo "Comment on #${{ github.event.issue.pull_request.url }} PR #${{ toJson(github) }}"
      - run: |
          echo "Status #${{ toJson(github) }}"
