name: OnCI
on:
  status
jobs:
  build:
    name: 'CI'
    if: ${{ contains(github.event.branches.*.name, 'staging_candidate') && (github.event.state == 'success' || github.event.state == 'failure') }}
    runs-on: ubuntu-latest
    steps:
#      - uses: actions/checkout@v2
#        with:
#          fetch-depth: 100
#          echo "Comment on #${{ github.event.issue.pull_request.url }} PR #${{ toJson(github) }}"
#          echo "Status #${{ toJson(github) }}"
      - run: |
          set -x
          prs=`gh api 'https://api.github.com/search/issues?q=repo:${{ github.repository }}+label:"staging+candidate"' -q '.items[]|[.url, .user.login]|@tsv'`
          if [ "${{github.event.state}}" == "success" ]; then
           echo "$prs" | while IFS=$'\t' read -r url login
            do
              echo "do something with $url $login";
              echo '{"labels":["Staging"]}' | gh api $url/labels --input -
              gh api -X DELETE $url/labels/staging\ candidate
            done
          else
           echo "$prs" | while IFS=$'\t' read -r url login
            do
              echo "do something with $url $login";
              gh api $url/comments -f "body=@$login stagin CI build failed"
            done
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
