name: OnCI
on:
  status
jobs:
  build:
    name: 'CI'
    if: ${{ contains(github.event.branches.*.name, 'staging_candidate') && (github.event.state == 'success' || github.event.state == 'failure') }}
    runs-on: ubuntu-latest
    steps:
#      - uses: actions/checkout@v2
#        with:
#          fetch-depth: 100
#          echo "Comment on #${{ github.event.issue.pull_request.url }} PR #${{ toJson(github) }}"
      - run: |
          set -x
          echo "Status #${{ toJson(github) }}"
          if [ "${{github.event.state}}" == "success" ]; then
            gh api 'https://api.github.com/search/issues?q=repo:${{ github.repository }}+label:"staging+candidate"' -q '.items[]|[.url, .user.login]|@sh' | while read -r input
            do
              echo "do something with $input";
              args=(input)
              url=input[1]
              echo '{"labels":["Staging"]}' | gh api $url/labels --input -
            done
          else
          fi
