name: 'Staging candidate build'
on:
  issue_comment:
    types: [created]
jobs:
  build:
    name: 'Staging candidate build'
    if: ${{ startsWith(github.event.comment.body, '/staging') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100
      - run: |
#          echo "${{ toJson(github) }}"
          set -xe
          gh api -X DELETE ${{ github.event.issue_url }}/labels/staging\ candidate
          gh api -X DELETE ${{ github.event.issue_url }}/labels/Staging
          new_branch=`gh api ${{ github.event.issue.pull_request.url }} --jq '.head.ref'`
          status_check=`gh api ${{ github.event.issue.repository_url }}/commits/$new_branch/status --jq '.state'`
          if [ "$status_check" != "success" ]; then
            gh api ${{ github.event.comment.reactions.url }} -f 'content=confused'
            gh api ${{ github.event.issue.comments_url }} -f "body=@${{ github.event.issue.user.login }} Please make sure CI is greeen"
            exit 1
          fi
          branches=`gh pr list -l staging | cut -d $'\t' -f 3 | sed "s/^/origin\//" | tr '\n' ' '`
          candidate_branches=`gh pr list -l 'staging candidate' | cut -d $'\t' -f 3 | sed "s/^/origin\//" | tr '\n' ' '`
          git fetch
          git config --global user.email "staging@indeedflex.com"
          git config --global user.name "Staging Candidate Action"
          git checkout -b staging_candidate
          set +e
          git merge --no-edit master $branches
          merge_staging_branches=$?
          set -e
          if [ $merge_staging_branches -ne 0 ];
          then
            printf "{\"body\": \"@${{ github.event.issue.user.login }} unable to merge 'Staging' PRs\\\n\`\`\`\\\ngit checkout master\\\ngit merge master $branches # <-- error, Staging\\\n\`\`\`\"}" | gh api ${{ github.event.issue.comments_url }} --input -
            exit 1
          fi
          set +e
          git merge --no-edit master $candidate_branches
          merge_staging_candidate_branches=$?
          set -e
          if [ $merge_staging_candidate_branches -ne 0 ];
          then
            printf "{\"body\": \"@${{ github.event.issue.user.login }} unable to merge 'staging candidate' PRs\\\n\`\`\`\\\ngit checkout master\\\ngit merge master $branches # Staging\\\ngit merge master $candidate_branches # <-- error, staging candidates\\\n\`\`\`\"}" | gh api ${{ github.event.issue.comments_url }} --input -
            exit 1
          fi
          set +e
          git merge --no-edit origin/$new_branch
          merge_current_branch=$?
          set -e
          if [ $merge_current_branch -ne 0 ];
          then
            printf "{\"body\": \"@${{ github.event.issue.user.login }} unable to merge the PR\\\n\`\`\`\\\ngit checkout master\\\ngit merge $branches # Staging\\\ngit merge $candidate_branches # staging candidates\\\ngit merge $new_branch # <-- error\\\n\`\`\`\"}" | gh api ${{ github.event.issue.comments_url }} --input -
            exit 1
          fi

          echo '{"labels":["staging candidate"]}' | gh api ${{ github.event.issue.url }}/labels --input -
          gh api ${{ github.event.comment.reactions.url }} -f 'content=rocket'
          git push -f --set-upstream origin staging_candidate

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
