name: 'Staging deploy'
on:
  status
jobs:
  deploy:
    name: 'Staging deploy'
    if: ${{ (github.event.commit.commit.message == 'staging_candidate') && (github.event.state == 'success' || github.event.state == 'failure') }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          set +x
          echo "${{ toJson(github) }}"
          set -x

          prs=`gh api 'https://api.github.com/search/issues?q=repo:${{ github.repository }}+label:"staging+candidate"' -q '.items[]|[.url, .user.login]|@tsv'`
          if [ -z "${prs}" ];
          then
            exit 0
          fi

          if [ "${{github.event.state}}" != "success" ]; then
           echo "$prs" | while IFS=$'\t' read -r url login
            do
              gh api -X DELETE $url/labels/staging\ candidate || true
              gh api $url/comments -f "body=@$login staging_candidate branch failed CI"
            done
           exit 0
          fi

      - uses: actions/checkout@v2
      - run: |
          if [ "${{github.event.state}}" == "success" && "${{github.event.context}}" == "coverage" ]; then
           echo "$prs" | while IFS=$'\t' read -r url login
            do
              echo '{"labels":["Staging"]}' | gh api $url/labels --input -
              gh api -X DELETE $url/labels/staging\ candidate
            done

           git remote set-branches origin staging_candidate
           git fetch
           git checkout staging_candidate
           git push -f origin origin/staging_candidate:staging1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
